export const ActionTypes = {
  FETCH_PHOTOS: 'FETCH_PHOTOS',
  FAIL_FETCHING_PHOTOS: 'FAIL_FETCHING_PHOTOS',
  POST_PHOTO: 'POST_PHOTO',
  SUCCESS_POSTING_PHOTO: 'SUCCESS_POSTING_PHOTO',
  FAIL_POSTING_PHOTO: 'FAIL_POSTING_PHOTO',
  GET_FILE_IMAGE_SRC: 'GET_FILE_IMAGE_SRC',
  CLEAR_FILE_IMAGE_SRC: 'CLEAR_FILE_IMAGE_SRC'
};
